{lib, ...}: {
  # Root filesystem F2FS options
  # Use mkForce to override options generated by hardware-configuration.nix
  fileSystems."/".options = lib.mkForce [
    "compress_algorithm=zstd:6"
    "compress_chksum"
    "atgc"
    "gc_merge"
    "lazytime"
  ];

  # F2FS maintenance and tools
  boot.supportedFilesystems = ["f2fs"];
}
